[plugins."io.containerd.grpc.v1.cri".registry]
  mirrors = {
    "localhost:5000" = {
      endpoint = ["http://k3d-registry.localhost:5000"]
    }
  }
  configs = {
    "localhost:5000" = {
      tls = {
        insecure_skip_verify = true
      }
    }
  }
