apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test-app
  namespace: helix-core
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`helix.local`)
      kind: Rule
      services:
        - name: traefik
          port: 9000
  tls:
    secretName: helix-local-cert
