additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"
  - "--entrypoints.websecure.http.tls=true"

service:
  type: NodePort

ports:
  web:
    port: 80
    expose:
      enabled: true
    exposedPort: 80
    protocol: TCP
    exposePort: true

  websecure:
    port: 443
    expose:
      enabled: true
    exposedPort: 443
    protocol: TCP
    exposePort: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure

logs:
  general:
    level: DEBUG
  access:
    enabled: true
tls:
  stores:
    default:
      defaultCertificate:
        secretName: helix-local-cert

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    tls:
      secretName: helix-local-cert
