apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: helixstack
servers: 1
agents: 1
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
