# services/postgresql/postgresql-values.yaml
auth:
  username: admin
  password: admin
  existingSecret: ""
  postgresPassword: "dbpass123"
primary:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: local-path
service:
  type: ClusterIP