# services/vault/vault-values.yaml
global:
  image:
    repository: hashicorp/vault
    tag: "1.19.0"
    pullPolicy: IfNotPresent

server:
  dataStorage:
    enabled: true
    size: 8Gi
    storageClass: local-path

  service:
    type: ClusterIP
    port: 8200

  # --- CORRECTED INGRESS SECTION ---
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: "helix-local-ca-issuer"
    hosts:
      - host: vault.helix.local
        paths:
          - / # <--- THIS IS THE ONLY CHANGE: JUST THE PATH STRING HERE
    tls:
      - secretName: helix-wildcard-tls
        hosts:
          - vault.helix.local
ui:
  enabled: true
  config:
    basePath: /vault-ui