# services/kafka/kafka.yaml

apiVersion: apps.v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: helix-core
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka.helix.local:9092,INTERNAL://kafka-0.kafka.helix-headless.helix-core.svc.cluster.local:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
