# services/kafka/schema-registry-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: helix-core
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://kafka.helix-core.svc.cluster.local:9092" # Use the client service
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry.helix.local"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
            # - name: KAFKA_BOOTSTRAP_SERVERS # <--- REMOVE OR COMMENT OUT THIS LINE
            #   value: "PLAINTEXT://kafka-headless.helix-core.svc.cluster.local:29092"
